fn main() {
    linker_be_nice();
    // make sure linkall.x is the last linker script (otherwise might cause problems with flip-link)
    println!("cargo:rustc-link-arg=-Tlinkall.x");

    // Mesh OTA: embed public key when MESH_OTA_PUBKEY_PATH points to pubkey.hex (64-char hex).
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let pubkey_rs = std::path::Path::new(&out_dir).join("mesh_ota_pubkey.rs");
    let bytes: [u8; 32] = if let Ok(path) = std::env::var("MESH_OTA_PUBKEY_PATH") {
        let hex_str = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("MESH_OTA_PUBKEY_PATH {}: {}", path, e));
        let hex_str = hex_str.trim();
        if hex_str.len() != 64 {
            panic!("pubkey.hex must be 64 hex chars, got {}", hex_str.len());
        }
        let mut b = [0u8; 32];
        for (i, c) in hex_str.as_bytes().chunks(2).enumerate() {
            let s = std::str::from_utf8(c).unwrap();
            b[i] = u8::from_str_radix(s, 16).unwrap_or_else(|_| panic!("invalid hex in pubkey: {}", s));
        }
        b
    } else {
        [0u8; 32]
    };
    let content = format!(
        "// Generated by build.rs. Do not edit.\npub const MESH_OTA_PUBKEY: [u8; 32] = {:?};\n",
        bytes
    );
    std::fs::write(&pubkey_rs, content).expect("write mesh_ota_pubkey.rs");

    // Mesh OTA sender: embed manifest (v, h, n, sig) when MESH_OTA_MANIFEST_PATH points to manifest.json.
    let manifest_rs = std::path::Path::new(&out_dir).join("mesh_ota_manifest.rs");
    let (version, hash_hex, n_chunks, sig_b64) = if let Ok(path) = std::env::var("MESH_OTA_MANIFEST_PATH") {
        let data = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("MESH_OTA_MANIFEST_PATH {}: {}", path, e));
        let v: serde_json::Value = serde_json::from_str(&data).expect("manifest.json invalid");
        let version = v.get("v").and_then(|x| x.as_str()).unwrap_or("").to_string();
        let hash_hex = v.get("h").and_then(|x| x.as_str()).unwrap_or("").to_string();
        let n_chunks = v.get("n").and_then(|x| x.as_u64()).unwrap_or(0) as u32;
        let sig_b64 = v.get("sig").and_then(|x| x.as_str()).unwrap_or("").to_string();
        (version, hash_hex, n_chunks, sig_b64)
    } else {
        (String::new(), String::new(), 0u32, String::new())
    };
    // Mesh OTA image: embed firmware binary when MESH_OTA_IMAGE_PATH is set.
    // The image is copied to OUT_DIR so include_bytes! can reference it.
    let image_rs = std::path::Path::new(&out_dir).join("mesh_ota_image.rs");
    let has_image = if let Ok(path) = std::env::var("MESH_OTA_IMAGE_PATH") {
        let image_bytes = std::fs::read(&path)
            .unwrap_or_else(|e| panic!("MESH_OTA_IMAGE_PATH {}: {}", path, e));
        let image_len = image_bytes.len();
        // Copy image to OUT_DIR for include_bytes!
        let image_bin = std::path::Path::new(&out_dir).join("mesh_ota_image.bin");
        std::fs::write(&image_bin, &image_bytes).expect("write mesh_ota_image.bin");
        // Recompute n_chunks from image size + CHUNK_SIZE=128
        let chunk_size: usize = 128;
        let computed_n_chunks = ((image_len + chunk_size - 1) / chunk_size) as u32;
        if n_chunks > 0 && n_chunks != computed_n_chunks {
            panic!(
                "manifest n_chunks={} but image needs {} (image_len={}, chunk_size={})",
                n_chunks, computed_n_chunks, image_len, chunk_size
            );
        }
        std::fs::write(
            &image_rs,
            format!(
                "// Generated by build.rs. Do not edit.\n\
                 pub const MESH_OTA_IMAGE: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/mesh_ota_image.bin\"));\n\
                 pub const MESH_OTA_IMAGE_LEN: usize = {};\n",
                image_len
            ),
        )
        .expect("write mesh_ota_image.rs");
        println!("cargo:rerun-if-changed={}", path);
        true
    } else {
        std::fs::write(
            &image_rs,
            "// Generated by build.rs. Do not edit.\n\
             pub const MESH_OTA_IMAGE: &[u8] = &[];\n\
             pub const MESH_OTA_IMAGE_LEN: usize = 0;\n",
        )
        .expect("write mesh_ota_image.rs");
        false
    };

    let manifest_content = format!(
        "// Generated by build.rs. Do not edit.\n\
         pub const MESH_OTA_VERSION: &str = {:?};\n\
         pub const MESH_OTA_HASH_HEX: &str = {:?};\n\
         pub const MESH_OTA_N_CHUNKS: u32 = {};\n\
         pub const MESH_OTA_SIG_B64: &str = {:?};\n\
         pub const MESH_OTA_HAS_IMAGE: bool = {};\n",
        version, hash_hex, n_chunks, sig_b64, has_image
    );
    std::fs::write(&manifest_rs, manifest_content).expect("write mesh_ota_manifest.rs");
}

fn linker_be_nice() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 1 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                what if what.starts_with("_defmt_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `defmt` not found - make sure `defmt.x` is added as a linker script and you have included `use defmt_rtt as _;`"
                    );
                    eprintln!();
                }
                "_stack_start" => {
                    eprintln!();
                    eprintln!("💡 Is the linker script `linkall.x` missing?");
                    eprintln!();
                }
                what if what.starts_with("esp_rtos_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `esp-radio` has no scheduler enabled. Make sure you have initialized `esp-rtos` or provided an external scheduler."
                    );
                    eprintln!();
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!();
                    eprintln!(
                        "💡 `embedded-test` not found - make sure `embedded-test.x` is added as a linker script for tests"
                    );
                    eprintln!();
                }
                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!();
                    eprintln!(
                        "💡 Did you forget the `esp-alloc` dependency or didn't enable the `compat` feature on it?"
                    );
                    eprintln!();
                }
                _ => (),
            },
            // we don't have anything helpful for "missing-lib" yet
            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=--error-handling-script={}",
        std::env::current_exe().unwrap().display()
    );
}
